### ISSUE TITLE
Conversion metrics

### ISSUE THREAD

**Issue by thomas536** [balajis/twitter-export#5]
What are the primary impact metrics for success and are there targets for them?

Given the api constraints seems like the most successful solutions might be based on a better understanding of the specific goals of the influencer and the makeup of their existing or future audience.

Is there a ranking for possible metrics, e.g.

- purely impressions
- conversions to following on one different platform (e.g. only subtack)
- conversions to following on multiple different platform (e.g. substack and ghost and ...)
- purely contact information (e.g. volunteering email addresses are ok)

Is the conversion rate to different platforms or general interest for folks adopting different platforms already known (i.e. expected low conversion rate vs high conversion rate could make a big difference on approach)?

Thanks!

**Comment by balajis** [comment]
> What are the primary impact metrics for success and are there targets for them?
If you have N followers, being able to get a good % of them onto an email list would be the primary metric for success.

**Comment by thomas536** [comment]
Excellent, thanks!
